source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
workspace 'Singularity.xcworkspace'
project 'Singularity.xcodeproj'

use_frameworks!
pod 'Alamofire', '~> 4.6'
pod 'ReachabilitySwift'
pod 'IQKeyboardManagerSwift', '~> 5.0'

target 'Singularity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Singularity
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.0'
  pod 'SDWebImage/GIF'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'SnapKit', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'pop', '~> 1.0'
  pod 'IBAnimatable'
  pod 'FMDB'

end

target 'core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  project 'core/core.xcodeproj'

  # Pods

end

