source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
workspace 'Singularity.xcworkspace'
project 'Singularity.xcodeproj'

use_frameworks!
pod 'Alamofire', '~> 4.6'
pod 'ReachabilitySwift'

target 'Singularity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Singularity
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.0'
  pod 'SDWebImage/GIF'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

end

target 'core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  project 'core/core.xcodeproj'

  # Pods

end

