source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
workspace 'Singularity.xcworkspace'
project 'Singularity.xcodeproj'

target 'Singularity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Singularity
  pod 'Alamofire', '~> 4.5'

end

target 'core' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  project 'core/core.xcodeproj'

  # Pods

end

